name: chats
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  firebase_auth: ^4.12.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  go_router: ^12.1.1
  equatable: ^2.0.5
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.1.1
  cloud_firestore: ^4.15.9
  cached_network_image: ^3.3.1
  auto_size_text: ^3.0.0
  another_flushbar: ^1.12.30
  image_picker: ^1.0.8
  firebase_storage: ^11.7.1
  permission_handler: ^11.3.1
  uuid: ^4.4.0
  flutter_slidable: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
