name: chats
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  go_router: ^12.1.1
  equatable: ^2.0.5
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.1.1
  cloud_firestore: ^5.0.1
  cached_network_image: ^3.3.1
  auto_size_text: ^3.0.0
  another_flushbar: ^1.12.30
  firebase_storage: ^12.0.1
  permission_handler: ^11.3.1
  uuid: ^4.4.0
  flutter_slidable: ^3.1.0
  intl: ^0.19.0
  geolocator: ^12.0.0
  google_maps_flutter: ^2.6.0
  widget_to_marker: ^1.0.4
  audio_waveforms: ^1.0.5
  flutter_cache_manager: ^3.3.2
  file_picker: ^8.0.5
  image_picker: ^1.1.2
  gallery_picker: ^0.5.1
  easy_image_viewer: ^1.5.1
  mime: ^1.0.5
  chewie: ^1.8.1
  video_player: ^2.9.1
  any_link_preview: ^3.0.2
  url_launcher: ^6.3.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
